package com.nc.sample.model;
// Generated Mar 26, 2019 10:59:02 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Contact generated by hbm2java
 */
@Entity
@Table(name = "contact", schema = "public")
public class Contact implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	private int id;
	private String email;
	private String name;
	private String phone;

	public Contact() {}
	public Contact(int id, String name) {this.id = id;this.name = name;}
    public Contact(int id, String name, String email, String phone) {
        this.id = id;this.name = name;this.email = email;this.phone = phone;
    }



    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    @Column(name = "id", nullable = false, columnDefinition="serial")
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "email", length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "phone", length = 20)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

}
