package com.nc.pbackup;
// Generated Apr 16, 2019 9:30:41 AM by Hibernate Tools 5.2.10.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MUserRolesId generated by hbm2java
 */
@Embeddable
public class MUserRolesId implements java.io.Serializable {

	private long roleId;
	private long userId;

	public MUserRolesId() {
	}

	public MUserRolesId(long roleId, long userId) {
		this.roleId = roleId;
		this.userId = userId;
	}

	@Column(name = "role_id", nullable = false)
	public long getRoleId() {
		return this.roleId;
	}

	public void setRoleId(long roleId) {
		this.roleId = roleId;
	}

	@Column(name = "user_id", nullable = false)
	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MUserRolesId))
			return false;
		MUserRolesId castOther = (MUserRolesId) other;

		return (this.getRoleId() == castOther.getRoleId()) && (this.getUserId() == castOther.getUserId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getRoleId();
		result = 37 * result + (int) this.getUserId();
		return result;
	}

}
