package com.nc.pbackup;
// Generated Apr 8, 2019 2:51:53 PM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "role", schema = "public")
public class Role implements java.io.Serializable {

	private int id;
	private String name;
	private Set<User> users = new HashSet<User>(0);

	public Role() {}
	public Role(String name) {this.name=name;}
	public Role(int id, String name) {this.id = id;this.name = name;}

	public Role(int id, String name, Set<User> users) {
		this.id = id;
		this.name = name;
		this.users = users;
	}

	@Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false,columnDefinition="serial")
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "user_role", schema = "public",
		joinColumns = { @JoinColumn(name = "role_id", nullable = false, updatable = false) },
		inverseJoinColumns = {@JoinColumn(name = "user_id", nullable = false, updatable = false) }
	)
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

}
