package com.nc.pbackup;
// Generated Apr 8, 2019 2:51:53 PM by Hibernate Tools 5.2.10.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", schema = "public")
public class User implements java.io.Serializable {

	private int id;
	private String email;
	private String password;
	private Set<Role> roles = new HashSet<Role>(0);

	public User() {}
	public User(String email, String password) {this.email = email;this.password = password;}
	public User(int id, String email, String password) {this.id = id;this.email = email;this.password = password;}

	public User(int id, String email, String password, Set<Role> roles) {
		this.id = id;this.email = email;this.password = password;this.roles = roles;
	}

	@Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false,columnDefinition="serial")
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "email", nullable = false)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "password", nullable = false, length = 60)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "user_role", schema = "public",
		joinColumns = { @JoinColumn(name = "user_id", nullable = false, updatable = false) },
		inverseJoinColumns = { @JoinColumn(name = "role_id", nullable = false, updatable = false) }
	)
	public Set<Role> getRoles() {
		return this.roles;
	}

	public void setRoles(Set<Role> roles) {
		this.roles = roles;
	}

}
