package com.nc.model;
// Generated Jun 4, 2019 11:34:05 AM by Hibernate Tools 5.2.10.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AdministratorAccount generated by hbm2java
 */
@Entity
@Table(name = "administrator_account", schema = "public")
public class AdministratorAccount implements java.io.Serializable {

	private int accountId;
	private String userId;
	private String password;
	private String email;
	private String nickName;
	private String useLanguage;
	private boolean systemed;
	private boolean deleted;
	private Date registerTime;
	private int registerAccountId;
	private Date updateTime;
	private int updateAccountId;

	public AdministratorAccount() {
	}

	public AdministratorAccount(int accountId, String userId, String nickName, String useLanguage, boolean systemed,
			boolean deleted, Date registerTime, int registerAccountId, Date updateTime, int updateAccountId) {
		this.accountId = accountId;
		this.userId = userId;
		this.nickName = nickName;
		this.useLanguage = useLanguage;
		this.systemed = systemed;
		this.deleted = deleted;
		this.registerTime = registerTime;
		this.registerAccountId = registerAccountId;
		this.updateTime = updateTime;
		this.updateAccountId = updateAccountId;
	}

	public AdministratorAccount(int accountId, String userId, String password, String email, String nickName,
			String useLanguage, boolean systemed, boolean deleted, Date registerTime, int registerAccountId,
			Date updateTime, int updateAccountId) {
		this.accountId = accountId;
		this.userId = userId;
		this.password = password;
		this.email = email;
		this.nickName = nickName;
		this.useLanguage = useLanguage;
		this.systemed = systemed;
		this.deleted = deleted;
		this.registerTime = registerTime;
		this.registerAccountId = registerAccountId;
		this.updateTime = updateTime;
		this.updateAccountId = updateAccountId;
	}

	@Id

	@Column(name = "account_id", unique = true, nullable = false)
	public int getAccountId() {
		return this.accountId;
	}

	public void setAccountId(int accountId) {
		this.accountId = accountId;
	}

	@Column(name = "user_id", nullable = false)
	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	@Column(name = "password")
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "email")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "nick_name", nullable = false)
	public String getNickName() {
		return this.nickName;
	}

	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	@Column(name = "use_language", nullable = false, length = 2)
	public String getUseLanguage() {
		return this.useLanguage;
	}

	public void setUseLanguage(String useLanguage) {
		this.useLanguage = useLanguage;
	}

	@Column(name = "systemed", nullable = false)
	public boolean isSystemed() {
		return this.systemed;
	}

	public void setSystemed(boolean systemed) {
		this.systemed = systemed;
	}

	@Column(name = "deleted", nullable = false)
	public boolean isDeleted() {
		return this.deleted;
	}

	public void setDeleted(boolean deleted) {
		this.deleted = deleted;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "register_time", nullable = false, length = 35)
	public Date getRegisterTime() {
		return this.registerTime;
	}

	public void setRegisterTime(Date registerTime) {
		this.registerTime = registerTime;
	}

	@Column(name = "register_account_id", nullable = false)
	public int getRegisterAccountId() {
		return this.registerAccountId;
	}

	public void setRegisterAccountId(int registerAccountId) {
		this.registerAccountId = registerAccountId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", nullable = false, length = 35)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "update_account_id", nullable = false)
	public int getUpdateAccountId() {
		return this.updateAccountId;
	}

	public void setUpdateAccountId(int updateAccountId) {
		this.updateAccountId = updateAccountId;
	}

}
