package com.nc.model;
// Generated Jun 4, 2019 11:25:13 AM by Hibernate Tools 5.2.10.Final

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.persistence.Version;

/**
 * MRole generated by hbm2java
 */
@Entity
@Table(name = "m_role", schema = "public", uniqueConstraints = { @UniqueConstraint(columnNames = "nid"),
		@UniqueConstraint(columnNames = "role_name") })
public class MRole implements java.io.Serializable {

	private long roleId;
	private Long version;
	private long createdBy;
	private Date createdDate;
	private long updatedBy;
	private Date updatedDate;
	private Serializable nid;
	private String description;
	private String roleName;
	private String status;
	private Set<MUserRoles> MUserRoleses = new HashSet<MUserRoles>(0);

	public MRole() {
	}

	public MRole(long roleId, long createdBy, Date createdDate, long updatedBy, Date updatedDate, Serializable nid,
			String roleName, String status) {
		this.roleId = roleId;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
		this.nid = nid;
		this.roleName = roleName;
		this.status = status;
	}

	public MRole(long roleId, long createdBy, Date createdDate, long updatedBy, Date updatedDate, Serializable nid,
			String description, String roleName, String status, Set<MUserRoles> MUserRoleses) {
		this.roleId = roleId;
		this.createdBy = createdBy;
		this.createdDate = createdDate;
		this.updatedBy = updatedBy;
		this.updatedDate = updatedDate;
		this.nid = nid;
		this.description = description;
		this.roleName = roleName;
		this.status = status;
		this.MUserRoleses = MUserRoleses;
	}

	@Id

	@Column(name = "role_id", unique = true, nullable = false)
	public long getRoleId() {
		return this.roleId;
	}

	public void setRoleId(long roleId) {
		this.roleId = roleId;
	}

	@Version
	@Column(name = "version")
	public Long getVersion() {
		return this.version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}

	@Column(name = "created_by", nullable = false)
	public long getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(long createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 29)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@Column(name = "updated_by", nullable = false)
	public long getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(long updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date", nullable = false, length = 29)
	public Date getUpdatedDate() {
		return this.updatedDate;
	}

	public void setUpdatedDate(Date updatedDate) {
		this.updatedDate = updatedDate;
	}

	@Column(name = "nid", unique = true, nullable = false)
	public Serializable getNid() {
		return this.nid;
	}

	public void setNid(Serializable nid) {
		this.nid = nid;
	}

	@Column(name = "description", length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "role_name", unique = true, nullable = false, length = 30)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@Column(name = "status", nullable = false, length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "MRole")
	public Set<MUserRoles> getMUserRoleses() {
		return this.MUserRoleses;
	}

	public void setMUserRoleses(Set<MUserRoles> MUserRoleses) {
		this.MUserRoleses = MUserRoleses;
	}

}
